trigger:
  batch: true
  branches:
    include:
    - main
    - release/3.0
    
pr:
  branches:
    include:
    - main
    - release/3.0

variables:
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - name: OfficialBuildId
      value: $(Build.BuildNumber)
    - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
      value: 1
    - name: DOTNET_MULTILEVEL_LOOKUP
      value: 0

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

stages:
- stage: Build
  jobs:
  - job: Windows_NT
    displayName: Windows Build
    pool:
      vmImage: windows-latest

    variables:
      BuildConfiguration: Release

    steps:
    - script: build.cmd -ci
        -configuration $(BuildConfiguration)
        -prepareMachine
        /p:BuildPackages=true
      displayName: Build

    - task: PublishBuildArtifacts@1
      displayName: Publish Build logs
      condition: always()
      inputs:
        pathToPublish: $(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)/
        artifactName: BuildLogs
        artifactType: container

    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)/artifacts/packages/$(BuildConfiguration)/Shipping
        targetFolder: $(Build.ArtifactStagingDirectory)/Packages

    - publish: $(Build.ArtifactStagingDirectory)/Packages
      displayName: Publish Build Artifacts
      artifact: BuildPackages

  - job: Linux
    displayName: Linux Build
    container: LinuxContainer
    pool:
      vmImage: ubuntu-latest

    variables:
      BuildConfiguration: Release

    steps:
    - script: ./build.sh --ci
        --configuration $(BuildConfiguration)
        --prepareMachine
      displayName: Build

    - task: PublishBuildArtifacts@1
      displayName: Publish Build logs
      condition: always()
      inputs:
        pathToPublish: $(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)/
        artifactName: BuildLogs
        artifactType: container

- stage: CodeSign
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - deployment: CodeSign
    displayName: Code Signing
    pool:
      vmImage: windows-latest    
    variables:
    - group: SignClient
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: custom
              custom: tool
              arguments: install --tool-path . SignClient
            displayName: Install SignTool tool

          - pwsh: |
              .\SignClient "Sign" `
              --baseDirectory "$(Pipeline.Workspace)\BuildPackages" `
              --input "**/*.nupkg" `
              --config "$(Pipeline.Workspace)\config\SignClient.json" `
              --filelist "$(Pipeline.Workspace)\config\filelist.txt" `
              --user "$(SignClientUser)" `
              --secret '$(SignClientSecret)' `
              --name "DotnetIoT" `
              --description "dotnet/iot" `
              --descriptionUrl "https://github.com/dotnet/iot"
            displayName: Sign packages
              
          - publish: $(Pipeline.Workspace)/BuildPackages
            displayName: Publish Signed Packages
            artifact: SignedPackages
